### ISSUE TITLE
Empty titles break dragging behavior

### ISSUE THREAD

**Issue by michealparks** [kitschpatrol/svelte-tweakpane-ui#1]
First of all, thank you for this amazing library!

Steps to reproduce:

```svelte
<script lang="ts">
  import { Pane } from 'svelte-tweakpane-ui';
</script>

<!-- I've done this to avoid the default title that comes up -->
<Pane title='' position='draggable'>
  ...
</Pane>
```

When this is done the pane is no longer draggable.

**Comment by kitschpatrol** [comment]
Good catch, thank you!

The div that acts as the drag handle was collapsing to zero height in the absence of the title. Fixed in 1.0.1.
