### ISSUE TITLE
Local forked build failing on patch

### ISSUE THREAD

**Issue by cristianvogel** [kitschpatrol/svelte-tweakpane-ui#14]
```
svelte-tweakpane-ui % pnpm install  
Scope: all 2 workspace projects
 ERR_PNPM_PATCH_NOT_APPLIED  The following patches were not applied: @astrojs/starlight@0.24.0
```

trying to build locally from fork, so I can tweak the tweakpane a bit... is this something I can get around?

**Comment by kitschpatrol** [comment]
Yes, a patch is out of sync with the latest version of what it's trying to patch. I've just now pinned the `@astrojs/starlight` dependency. Please pull the latest commit from main and give it another shot. Let me know if you run into additional issues or have any questions.

You will likely see a warning like below while running `pnpm install`, but it's not important and is pending a fix in the dependent library:

```
└─┬ @kitschpatrol/shared-config 4.7.1
  ├─┬ @kitschpatrol/eslint-config 4.7.1
  │ └─┬ eslint-plugin-perfectionist 2.10.0
  │   └── ✕ unmet peer astro-eslint-parser@^0.16.0: found 1.0.2 in @kitschpatrol/eslint-config
```

**Comment by kitschpatrol** [comment]
Please re-open if you're still having trouble building the project, or if you have other questions.

**Comment by cristianvogel** [comment]
What I was working on is up now,  https://nel-shifter-mesh.vercel.app/

Thanks for all the help, I gave this project front page acknowledgement!

**Comment by kitschpatrol** [comment]
Congrats on the launch, and thanks for the acknowledgement. The theme looks really good!
