### ISSUE TITLE
More integrated plugins

### ISSUE THREAD

**Issue by amiacylon** [kitschpatrol/svelte-tweakpane-ui#19]
Hi, now tweakpane-plugin-inputs and tweakpane-plugin-file-import are both update for v4, it would be great to get them integrated.  I also need a palette selector so will take a look at forking tweakpane-plugin-chromatic and updating it for v4

**Comment by kitschpatrol** [comment]
Hi, thanks — it's helpful to know which plugins people want.

Adding links for my future reference:

- https://github.com/LuchoTurtle/tweakpane-plugin-file-import
- https://github.com/tallneil/tweakpane-plugin-inputs
- https://github.com/brunoimbrizi/tweakpane-plugin-chromatic

**Comment by amiacylon** [comment]
Thanks, a tree view would also be great but seems there is only a very old plugin for that and it has no repo https://www.npmjs.com/package/tweakpane-treeview-plugin/v/1.0.14?activeTab=code

**Comment by kitschpatrol** [comment]
New components incorporating functionality from [tweakpane-plugin-file-import](https://github.com/LuchoTurtle/tweakpane-plugin-file-import) and [tweakpane-plugin-inputs](https://github.com/tallneil/tweakpane-plugin-inputs) are now available in Svelte Tweakpane UI [v1.5.0](https://github.com/kitschpatrol/svelte-tweakpane-ui/releases/tag/v1.5.0):

- [`<Stepper>`](https://kitschpatrol.com/svelte-tweakpane-ui/docs/components/stepper)
- [`<File>`](https://kitschpatrol.com/svelte-tweakpane-ui/docs/components/file)

I'll keep an eye out for your updates to the chromatic plugin.

**Comment by amiacylon** [comment]
Great! I will try and work on chromatic during my Christmas time off!
