### ISSUE TITLE
How do I hide the value field on a slider

### ISSUE THREAD

**Issue by cristianvogel** [kitschpatrol/svelte-tweakpane-ui#8]
Excellent UI library and documentation, thankyou so much !

I just can't seem to do this simple thing, and that is to hide the value readout box next to a slider if necessary. Aplogies up front if I missed it and its really obvious.

**Comment by kitschpatrol** [comment]
Hey Christian, thanks for using the library!

Good question, to my knowledge there's not actually an "official" way to do this through the [Tweakpane API](https://tweakpane.github.io/docs/api/classes/SliderBladeApi.html#element), so I haven't exposed a prop for this.

But it looks like something that can actually be accomplished pretty easily with CSS, so I'll look into that approach and see if I can add a prop for it to the `<Slider>` component.

I should have a minute to mess with this in the next few days.

**Comment by kitschpatrol** [comment]
Ok, I added a `wide` prop to `<Slider>` and `<SliderInterval>` which hides the numeric input field when set to `true`.

It's named for consistency with a similar option included in the CameraKit plugin controls from the original Tweakpane author.

This is included in [release v1.3.0](https://github.com/kitschpatrol/svelte-tweakpane-ui/releases/tag/v1.3.0).

Also added a [demo to the documentation site](https://kitschpatrol.com/svelte-tweakpane-ui/docs/features#wide-sliders).

Thanks for suggesting this!
